development:
  adapter: mysql2
  database: lunchroullette_development
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8
  collation: utf8_general_ci

test:
  adapter: mysql2
  database: lunchroullette_test
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8
  collation: utf8_general_ci

production:
  adapter: mysql2
  database: lunchroullette_production
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8
  collation: utf8_general_ci

